image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - docker login -u martin@martincarlin.uk -p $CI_BUILD_TOKEN
    - docker push registry.gitlab.com/martincarlin87/martincarlin.uk
    - docker-compose up --force-recreate
