image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD registry.gitlab.com
    - docker tag ghost registry.gitlab.com/martincarlin87/martincarlin.uk/ghost:latest
    - docker tag mariadb:10.3 registry.gitlab.com/martincarlin87/martincarlin.uk/mariadb:latest
    - docker push registry.gitlab.com/martincarlin87/martincarlin.uk
    - ssh martin@$CI_DEPLOY_IP
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD registry.gitlab.com
    - docker stop registry.gitlab.com/martincarlin87/martincarlin.uk/ghost:latest
    - docker stop mariadb:10.3 registry.gitlab.com/martincarlin87/martincarlin.uk/mariadb:latest
    - docker rm registry.gitlab.com/martincarlin87/martincarlin.uk/ghost:latest
    - docker rm registry.gitlab.com/martincarlin87/martincarlin.uk/mariadb:latest
    - docker pull registry.gitlab.com/martincarlin87/martincarlin.uk/ghost:latest
    - docker pull registry.gitlab.com/martincarlin87/martincarlin.uk/mariadb:latest
    - docker-compose up --force-recreate