image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
  script:
    - docker login registry.gitlab.com -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD
    - docker tag ghost registry.gitlab.com/martincarlin87/martincarlin.uk/ghost:latest
    - docker tag mariadb:10.3 registry.gitlab.com/martincarlin87/martincarlin.uk/mariadb:latest
    - docker push registry.gitlab.com/martincarlin87/martincarlin.uk
