image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

stages:
  - build
  - deploy

build:
 stage: build
 script:
   - docker-compose build

deploy:
  stage: deploy
  script:
    - docker-compose up --force-recreate
