version: '3.1'

services:

  mysql:
    container_name: ghost_mysql
    image: mariadb:10.3
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/martincarlin.sql:/docker-entrypoint-initdb.d/martincarlin.sql
    networks:
      - web-network

  ghost:
    container_name: ghost
    image: ghost
    restart: always
    depends_on:
      - mysql
    ports:
      - ${HOST_PORT}:2368
    volumes:
      - ./content:/var/lib/ghost/content
      - ./config.production.json:/var/lib/ghost/config.production.json
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: ${MYSQL_USER}
      database__connection__password: ${MYSQL_PASSWORD}
      database__connection__database: ${MYSQL_DATABASE}
      server__host: 0.0.0.0
      url: ${URL}
      NODE_ENV: production
      LOGGING_LEVEL: error
    command: ["node", "current/index.js"]
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
