routes:

  /:
    data: page.home
    template: home

  /about/:
    data: page.about
    template: about

  /cv-and-skills/:
    data: page.cv-and-skills
    template: cv-and-skills

  /blog/:
    data: page.blog
    template: blog

  /contact/:
    data: page.contact
    template: contact

collections:
  /:
    permalink: /{year}/{month}/{day}/{slug}/ 
    template:
      - index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
